CREATE TABLE public.users (
  id serial primary key,
  name VARCHAR(64) NOT NULL UNIQUE,
  username character varying(64) NOT NULL,
  password character varying(256) NOT NULL,
  isAdmin BOOLEAN DEFAULT FALSE
);

CREATE TABLE public.events (
  id SERIAL PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  slug VARCHAR(64) NOT NULL UNIQUE,
  description TEXT,
  maker INTEGER NOT NULL DEFAULT 1,
  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT maker FOREIGN KEY (maker) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE public.registrations (
  id SERIAL PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  comment TEXT,
  event INTEGER NOT NULL,
  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT event FOREIGN KEY (event) REFERENCES events(id) ON DELETE CASCADE
);

